using Bunit;
using Microsoft.AspNetCore.Components;
using TwBlazor.Components;

namespace TwBlazor.Tests.Components.DataTable;

public class TwDataTableManualRenderingTests : TwBlazorTestBase
{
    [Fact]
    public void TwDataTable_ManualTableHeader_RendersCustomHeader()
    {
        // Arrange
        var products = GetTestProducts();
        RenderFragment tableHeader = builder =>
        {
            builder.OpenElement(0, "th");
            builder.AddContent(1, "Custom Header");
            builder.CloseElement();
        };

        // Act
        var cut = TestContext.Render<TwDataTable<TestProduct>>(parameters => parameters
            .Add(p => p.Items, products)
            .Add(p => p.TableHeader, tableHeader)
            .Add(p => p.TableRow, RenderTableRow));

        // Assert
        var header = cut.Find("th");
        Assert.Contains("Custom Header", header.TextContent);
    }

    [Fact]
    public void TwDataTable_ManualTableRow_RendersCustomCells()
    {
        // Arrange
        var products = GetTestProducts();
        RenderFragment tableHeader = builder =>
        {
            builder.OpenElement(0, "th");
            builder.AddContent(1, "Name");
            builder.CloseElement();
        };

        // Act
        var cut = TestContext.Render<TwDataTable<TestProduct>>(parameters => parameters
            .Add(p => p.Items, products)
            .Add(p => p.TableHeader, tableHeader)
            .Add(p => p.TableRow, RenderTableRow));

        // Assert
        var cells = cut.FindAll("td");
        Assert.Equal(3, cells.Count);
        Assert.Contains("Laptop", cells[0].TextContent);
    }

    [Fact]
    public void TwDataTable_DefineTableRows_AllowsCustomTrElements()
    {
        // Arrange
        var products = GetTestProducts();
        RenderFragment tableHeader = builder =>
        {
            builder.OpenElement(0, "th");
            builder.AddContent(1, "Name");
            builder.CloseElement();
        };

        RenderFragment<TestProduct> customRowWithTr = context => builder =>
        {
            builder.OpenElement(0, "tr");
            builder.AddAttribute(1, "class", "custom-row");
            builder.OpenElement(2, "td");
            builder.AddContent(3, context.Name);
            builder.CloseElement();
            builder.CloseElement();
        };

        // Act
        var cut = TestContext.Render<TwDataTable<TestProduct>>(parameters => parameters
            .Add(p => p.Items, products)
            .Add(p => p.TableHeader, tableHeader)
            .Add(p => p.TableRow, customRowWithTr)
            .Add(p => p.DefineTableRows, true));

        // Assert
        var rows = cut.FindAll("tbody tr");
        Assert.All(rows, row => Assert.Contains("custom-row", row.GetAttribute("class")));
    }

    [Fact]
    public void TwDataTable_RowClass_AppliesClassToAutoGeneratedRows()
    {
        // Arrange
        var products = GetTestProducts();
        RenderFragment tableHeader = builder =>
        {
            builder.OpenElement(0, "th");
            builder.AddContent(1, "Name");
            builder.CloseElement();
        };

        // Act
        var cut = TestContext.Render<TwDataTable<TestProduct>>(parameters => parameters
            .Add(p => p.Items, products)
            .Add(p => p.TableHeader, tableHeader)
            .Add(p => p.TableRow, RenderTableRow)
            .Add(p => p.RowClass, "my-row-class"));

        // Assert
        var rows = cut.FindAll("tbody tr");
        Assert.All(rows, row => Assert.Contains("my-row-class", row.GetAttribute("class")));
    }

    [Fact]
    public void TwDataTable_MixColumnsAndManual_PrefersColumns()
    {
        // Arrange
        var products = GetTestProducts();
        List<TwDataTableColumn<TestProduct>> columns =
        [
            new() { Name = "name", Title = "Product Name", PropertySelector = p => p.Name }
        ];

        RenderFragment manualHeader = builder =>
        {
            builder.OpenElement(0, "th");
            builder.AddContent(1, "Manual Header");
            builder.CloseElement();
        };

        // Act
        var cut = TestContext.Render<TwDataTable<TestProduct>>(parameters => parameters
            .Add(p => p.Items, products)
            .Add(p => p.Columns, columns)
            .Add(p => p.TableHeader, manualHeader));

        // Assert - Should use Columns, not manual header
        var header = cut.Find("th");
        Assert.Contains("Product Name", header.TextContent);
        Assert.DoesNotContain("Manual Header", header.TextContent);
    }

    [Fact]
    public void TwDataTable_NullItems_HandledGracefully()
    {
        // Arrange & Act
        var cut = TestContext.Render<TwDataTable<TestProduct>>(parameters => parameters
            .Add(p => p.Items, [null!]));

        // Assert - Should not throw, should render without the null item
        var rows = cut.FindAll("tbody tr");
        Assert.Empty(rows);
    }

    [Fact]
    public void TwDataTable_HeaderClass_AppliesCustomHeaderStyling()
    {
        // Arrange
        var products = GetTestProducts();
        List<TwDataTableColumn<TestProduct>> columns =
        [
            new()
            {
                Name = "name",
                Title = "Name",
                PropertySelector = p => p.Name,
                HeaderClass = "bg-blue-500 text-white"
            }
        ];

        // Act
        var cut = TestContext.Render<TwDataTable<TestProduct>>(parameters => parameters
            .Add(p => p.Items, products)
            .Add(p => p.Columns, columns));

        // Assert
        var header = cut.Find("th");
        Assert.Contains("bg-blue-500", header.GetAttribute("class"));
        Assert.Contains("text-white", header.GetAttribute("class"));
    }

    [Fact]
    public void TwDataTable_CellClass_AppliesCustomCellStyling()
    {
        // Arrange
        var products = GetTestProducts();
        List<TwDataTableColumn<TestProduct>> columns =
        [
            new()
            {
                Name = "name",
                Title = "Name",
                PropertySelector = p => p.Name,
                CellClass = "font-bold text-lg"
            }
        ];

        // Act
        var cut = TestContext.Render<TwDataTable<TestProduct>>(parameters => parameters
            .Add(p => p.Items, products)
            .Add(p => p.Columns, columns));

        // Assert
        var cells = cut.FindAll("td");
        Assert.All(cells, cell =>
        {
            Assert.Contains("font-bold", cell.GetAttribute("class"));
            Assert.Contains("text-lg", cell.GetAttribute("class"));
        });
    }

    [Fact]
    public void TwDataTable_CellFormatter_OverridesPropertySelector()
    {
        // Arrange
        var products = GetTestProducts();
        List<TwDataTableColumn<TestProduct>> columns =
        [
            new()
            {
                Name = "price",
                Title = "Price",
                PropertySelector = p => p.Price,
                CellFormatter = p => $"£{p.Price:N2}"
            }
        ];

        // Act
        var cut = TestContext.Render<TwDataTable<TestProduct>>(parameters => parameters
            .Add(p => p.Items, products)
            .Add(p => p.Columns, columns));

        // Assert
        var cells = cut.FindAll("td");
        Assert.All(cells, cell => Assert.Contains("£", cell.TextContent));
    }

    [Fact]
    public void TwDataTable_EmptyColumns_FallsBackToManualRendering()
    {
        // Arrange
        var products = GetTestProducts();
        RenderFragment tableHeader = builder =>
        {
            builder.OpenElement(0, "th");
            builder.AddContent(1, "Manual");
            builder.CloseElement();
        };

        // Act
        var cut = TestContext.Render<TwDataTable<TestProduct>>(parameters => parameters
            .Add(p => p.Items, products)
            .Add(p => p.Columns, [])
            .Add(p => p.TableHeader, tableHeader)
            .Add(p => p.TableRow, RenderTableRow));

        // Assert
        var header = cut.Find("th");
        Assert.Contains("Manual", header.TextContent);
    }

    // Helper methods
    private static RenderFragment<TestProduct> RenderTableRow => context => builder =>
    {
        builder.OpenElement(0, "td");
        builder.AddContent(1, context.Name);
        builder.CloseElement();
    };

    private static List<TestProduct> GetTestProducts()
    {
        return
        [
            new() { Id = 1, Name = "Laptop", Price = 999.99m },
            new() { Id = 2, Name = "Mouse", Price = 29.99m },
            new() { Id = 3, Name = "Keyboard", Price = 79.99m }
        ];
    }

    public class TestProduct
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public decimal Price { get; set; }
    }
}
