// Inputs only. The expected value of every case is produced by the real tailwind-merge package in gen.mjs.
export const corpus = {
    Merge_MatchesTailwindMerge_ForClassGroupConflicts: [
        'grow grow-[2]',
        'overflow-x-auto overflow-x-hidden',
        'basis-full basis-auto',
        'w-full w-fit',
        'overflow-x-auto overflow-x-hidden overflow-x-scroll',
        'overflow-x-auto hover:overflow-x-hidden overflow-x-scroll',
        'overflow-x-auto hover:overflow-x-hidden hover:overflow-x-auto overflow-x-scroll',
        'col-span-1 col-span-full',
        'gap-2 gap-px basis-px basis-3',
        'lining-nums tabular-nums diagonal-fractions',
        'normal-nums tabular-nums diagonal-fractions',
        'tabular-nums diagonal-fractions normal-nums',
        'tabular-nums proportional-nums',
        'lining-nums oldstyle-nums ordinal slashed-zero',
        'line-clamp-1 line-clamp-2',
        'line-clamp-4 line-clamp-none',
        'aspect-auto aspect-square aspect-video',
        'aspect-square aspect-[4/3]',
        'columns-2 columns-xs',
        'box-border box-content',
        'float-left float-right float-none',
        'float-start float-end clear-start clear-end',
        'clear-left clear-both',
        'isolate isolation-auto',
        'object-cover object-contain',
        'object-center object-top',
        'object-cover object-top',
        'static fixed absolute relative sticky',
        'visible invisible collapse',
        'collapse visible',
        'z-10 z-auto',
        'basis-1/2 basis-full',
        'flex-row flex-col',
        'flex-wrap flex-nowrap',
        'flex-1 flex-auto flex-none',
        'flex-row flex-wrap flex-1',
        'grow grow-0',
        'shrink shrink-0',
        'order-1 order-last order-none',
        'grid-cols-2 grid-cols-none',
        'grid-cols-2 grid-cols-subgrid',
        'grid-rows-3 grid-rows-subgrid',
        'col-auto col-span-2',
        'col-start-1 col-start-auto',
        'col-end-3 col-end-auto',
        'row-auto row-span-2',
        'row-start-1 row-start-2 row-end-3 row-end-4',
        'col-span-full col-2 row-span-3 row-4',
        'grid-flow-row grid-flow-col-dense',
        'auto-cols-auto auto-cols-fr',
        'auto-rows-min auto-rows-max',
        'justify-start justify-between',
        'justify-normal justify-center justify-stretch',
        'justify-items-start justify-items-center',
        'justify-self-auto justify-self-end',
        'content-center content-between',
        'content-normal content-center content-stretch',
        'items-start items-baseline',
        'items-baseline items-baseline-last',
        'items-center-safe items-baseline items-end-safe',
        'self-auto self-stretch',
        'self-baseline self-baseline-last',
        'place-content-center place-content-between',
        'place-content-center place-content-end-safe place-content-center-safe',
        'place-items-start place-items-end',
        'place-self-auto place-self-center',
        'size-4 size-full',
        'w-4 w-screen w-min w-max w-fit',
        'h-svh h-dvh w-svw w-dvw',
        'h-10 h-min',
        'h-12 h-lh',
        'min-h-12 min-h-lh',
        'max-h-12 max-h-lh',
        'min-w-0 min-w-50 min-w-px',
        'max-w-sm max-w-prose max-w-screen-md',
        'min-h-0 min-h-full min-h-screen',
        'max-h-4 max-h-full',
        'table-auto table-fixed',
        'caption-top caption-bottom',
        'border-collapse border-separate',
        'border-spacing-2 border-spacing-4',
        'transition transition-colors transition-none',
        'duration-75 duration-1000',
        'ease-in ease-out ease-linear',
        'delay-150 delay-0 duration-150 duration-0',
        'animate-spin animate-none',
        'origin-center origin-top-left',
        'cursor-pointer cursor-wait',
        'pointer-events-none pointer-events-auto',
        'resize resize-none resize-y',
        'select-none select-text select-all',
        'appearance-none appearance-auto',
        'will-change-auto will-change-transform',
        'accent-red-500 accent-auto',
        'caret-red-500 caret-transparent',
        'scroll-auto scroll-smooth',
        'snap-start snap-center',
        'snap-normal snap-always',
        'snap-x snap-y snap-none',
        'snap-mandatory snap-proximity',
        'touch-auto touch-none',
        'forced-color-adjust-auto forced-color-adjust-none',
        'field-sizing-content field-sizing-fixed',
        'scheme-normal scheme-dark',
        'sr-only not-sr-only',
        'mix-blend-normal mix-blend-multiply',
        'bg-blend-normal bg-blend-multiply',
        'opacity-0 opacity-50',
        'fill-red-500 fill-none',
        'stroke-black stroke-1',
        'stroke-2 stroke-[3]',
        'stroke-red-500 stroke-blue-500',
        'hyphens-auto hyphens-manual',
        'whitespace-nowrap whitespace-break-spaces',
        'break-normal break-words break-all',
        'wrap-break-word wrap-normal wrap-anywhere',
        'break-after-auto break-after-page',
        'break-before-auto break-before-column',
        'break-inside-auto break-inside-avoid',
        'box-decoration-clone box-decoration-slice',
        'indent-4 indent-px',
        'align-baseline align-middle',
        'list-disc list-decimal list-none',
        'list-inside list-outside',
        'list-disc list-inside',
        'list-image-none list-image-[url(./my-image.png)] list-image-[var(--value)]',
        'overscroll-auto overscroll-contain',
        'overscroll-x-auto overscroll-y-none overscroll-none',
    ],
    Merge_MatchesTailwindMerge_ForConflictsAcrossClassGroups: [
        'inset-1 inset-x-1',
        'inset-x-1 inset-1',
        'inset-x-1 left-1 inset-1',
        'inset-x-1 inset-1 left-1',
        'inset-x-1 right-1 inset-1',
        'inset-x-1 right-1 inset-x-1',
        'inset-x-1 right-1 inset-y-1',
        'right-1 inset-x-1 inset-y-1',
        'inset-x-1 hover:left-1 inset-1',
        'start-1 end-1 inset-x-2',
        'top-1 bottom-1 inset-y-2',
        'inset-s-1 inset-e-1 inset-x-2',
        'ring shadow',
        'ring-2 shadow-md',
        'shadow ring',
        'shadow-md ring-2',
        'touch-pan-x touch-pan-right',
        'touch-none touch-pan-x',
        'touch-pan-x touch-none',
        'touch-pan-x touch-pan-y touch-pinch-zoom',
        'touch-manipulation touch-pan-x touch-pan-y touch-pinch-zoom',
        'touch-pan-x touch-pan-y touch-pinch-zoom touch-auto',
        'overflow-auto inline line-clamp-1',
        'line-clamp-1 overflow-auto inline',
        'p-1 px-2 py-3 pt-4 pr-5 pb-6 pl-7 ps-8 pe-9',
        'pt-4 pr-5 pb-6 pl-7 ps-8 pe-9 px-2 py-3 p-1',
        'ps-2 pe-2 px-4',
        'pl-2 pr-2 ps-4 pe-4',
        'm-1 mx-2 my-3 mt-4 mr-5 mb-6 ml-7 ms-8 me-9',
        'mt-4 mr-5 mb-6 ml-7 ms-8 me-9 mx-2 my-3 m-1',
        'ms-2 me-2 mx-4',
        'gap-x-2 gap-y-4 gap-1',
        'gap-1 gap-x-2 gap-y-4',
        'overflow-x-auto overflow-y-auto overflow-hidden',
        'overflow-hidden overflow-x-auto',
        'overscroll-x-auto overscroll-y-auto overscroll-contain',
        'w-4 h-6 size-8',
        'size-8 w-4 h-6',
        'size-10 w-12',
        'scale-x-50 scale-y-75 scale-100',
        'scale-100 scale-x-50',
        'translate-x-2 translate-y-4 translate-6',
        'translate-6 translate-x-2',
        'translate-none translate-x-2',
        'translate-x-2 translate-none',
        'rotate-12 rotate-x-2 rotate-none rotate-y-3',
        'skew-x-2 skew-y-4 skew-6',
        'skew-6 skew-x-2',
        'rounded-tl-sm rounded-tr-sm rounded-t-lg',
        'rounded-t-lg rounded-tl-sm',
        'rounded-s-sm rounded-ss-lg rounded-es-lg',
        'rounded-ss-lg rounded-es-lg rounded-s-sm',
        'rounded-se-lg rounded-ee-lg rounded-e-sm',
        'rounded-tr-lg rounded-br-lg rounded-r-sm',
        'rounded-br-lg rounded-bl-lg rounded-b-sm',
        'rounded-tl-lg rounded-bl-lg rounded-l-sm',
        'rounded-t rounded-r rounded-b rounded-l rounded-full',
        'rounded-full rounded-t rounded-r rounded-b rounded-l',
        'rounded-ss rounded-se rounded-ee rounded-es rounded-none',
        'border-spacing-x-2 border-spacing-y-4 border-spacing-1',
        'border-spacing-1 border-spacing-x-2',
        'border-t border-r border-b border-l border-4',
        'border-4 border-t border-r border-b border-l',
        'border-s-2 border-e-2 border-x-4',
        'border-s-2 border-e-2 border-4',
        'border-x-2 border-y-4 border',
        'border-t-2 border-b-2 border-y-4',
        'border-t-red-500 border-b-red-500 border-y-blue-500',
        'border-l-red-500 border-r-red-500 border-x-blue-500',
        'border-s-red-500 border-e-red-500 border-x-blue-500',
        'border-x-red-500 border-y-red-500 border-blue-500',
        'scroll-m-4 scroll-mx-2 scroll-mt-1',
        'scroll-mt-1 scroll-mx-2 scroll-m-4',
        'scroll-ml-1 scroll-mr-1 scroll-mx-2',
        'scroll-mt-1 scroll-mb-1 scroll-my-2',
        'scroll-ms-1 scroll-me-1 scroll-m-2',
        'scroll-p-4 scroll-px-2 scroll-pt-1',
        'scroll-pt-1 scroll-px-2 scroll-p-4',
        'scroll-pl-1 scroll-pr-1 scroll-px-2',
        'scroll-pt-1 scroll-pb-1 scroll-py-2',
        'scroll-ps-1 scroll-pe-1 scroll-p-2',
        'flex-row flex-1 flex-wrap basis-4 grow shrink',
        'basis-4 grow shrink flex-1',
        'flex-1 basis-4 grow shrink',
        'col-start-1 col-end-3 col-span-2',
        'col-span-2 col-start-1 col-end-3',
        'row-start-1 row-end-3 row-span-2',
        'place-content-center content-start justify-end',
        'content-start justify-end place-content-center',
        'place-items-center items-start justify-items-end',
        'items-start justify-items-end place-items-center',
        'place-self-center self-start justify-self-end',
        'self-start justify-self-end place-self-center',
        'truncate overflow-visible',
        'overflow-visible truncate',
        'truncate text-clip whitespace-normal',
        'text-clip whitespace-normal truncate',
        'text-ellipsis truncate',
        'space-x-2 space-x-4 space-y-1 space-y-3',
        'space-x-reverse space-x-2 space-y-reverse',
        'divide-x-2 divide-x-4 divide-y divide-y-0',
        'divide-x-reverse divide-x-2 divide-y-reverse',
        'divide-solid divide-dashed divide-red-500 divide-blue-500',
        'transform transform-gpu transform-none',
        'transform-3d transform-flat',
        'transform-cpu transform-gpu',
        'perspective-dramatic perspective-none perspective-midrange',
        'perspective-origin-center perspective-origin-top-left',
        'backface-visible backface-hidden',
        'underline-offset-2 underline-offset-4 decoration-1 decoration-2',
        'decoration-red-500 decoration-2 decoration-wavy decoration-blue-500 decoration-4 decoration-dotted',
        'decoration-auto decoration-from-font',
        'outline outline-2 outline-dashed outline-red-500 outline-offset-2 outline-offset-4',
        'outline-black outline-1',
        'outline-none outline-hidden outline-solid',
        'outline-2 outline-none',
        'ring ring-2 ring-inset ring-red-500 ring-blue-500 ring-offset-2 ring-offset-4 ring-offset-white ring-offset-black',
        'ring-4 ring-orange inset-ring inset-ring-3 inset-ring-blue',
        'inset-shadow-sm inset-shadow-md inset-shadow-red-500 inset-shadow-blue-500',
        'shadow shadow-sm shadow-inner shadow-none',
        'shadow-md shadow-red-500/50 shadow-lg shadow-blue-500',
        'shadow-md shadow-lg/25 text-shadow-md text-shadow-lg/25',
        'text-shadow-none text-shadow-2xl',
        'text-shadow-none text-shadow-md text-shadow-red text-shadow-red-500 shadow-red shadow-3xs',
        'drop-shadow-some-color drop-shadow-[#123456] drop-shadow-lg drop-shadow-[10px_0]',
        'drop-shadow-[#123456] drop-shadow-some-color',
        'drop-shadow-2xl drop-shadow-[shadow:foo]',
        'drop-shadow drop-shadow-md drop-shadow-none',
        'filter filter-none',
        'blur blur-sm blur-none',
        'brightness-50 brightness-150',
        'contrast-50 contrast-200',
        'grayscale grayscale-0',
        'grayscale-0 grayscale-[50%]',
        'hue-rotate-15 hue-rotate-180',
        'invert invert-0',
        'saturate-50 saturate-200',
        'sepia sepia-0',
        'backdrop-filter backdrop-filter-none',
        'backdrop-blur backdrop-blur-sm backdrop-brightness-50 backdrop-brightness-150',
        'backdrop-contrast-50 backdrop-contrast-200 backdrop-grayscale backdrop-grayscale-0',
        'backdrop-hue-rotate-15 backdrop-hue-rotate-180 backdrop-invert backdrop-invert-0',
        'backdrop-opacity-50 backdrop-opacity-100 backdrop-saturate-50 backdrop-saturate-200 backdrop-sepia backdrop-sepia-0',
        'mask-add mask-subtract',
        'mask-(--foo) mask-[foo] mask-none',
        'mask-linear-1 mask-linear-2',
        'mask-type-luminance mask-type-alpha',
        'mask-clip-border mask-clip-padding mask-origin-border mask-origin-content',
        'mask-no-repeat mask-repeat mask-cover mask-contain mask-center mask-top',
    ],
    Merge_MatchesTailwindMerge_ForTypography: [
        'text-sm text-lg text-2xl',
        'text-xs text-base',
        'text-3.5xl text-black',
        'text-red-500 text-blue-600 text-current text-transparent',
        'text-red text-secret-sauce',
        'text-sm text-secret-sauce',
        'text-left text-center text-right text-justify text-start text-end',
        'text-wrap text-pretty',
        'text-balance text-pretty',
        'text-wrap text-nowrap text-center',
        'text-ellipsis text-clip',
        'text-lg/7 text-lg/8',
        'text-lg/none leading-9',
        'leading-9 text-lg/none',
        'text-sm leading-6 text-lg/7',
        'leading-6 text-lg',
        'text-lg leading-6',
        'leading-6 text-red-500',
        'leading-none leading-tight leading-[1.5]',
        'tracking-tight tracking-wide tracking-[0.2em]',
        'font-thin font-black',
        'font-medium font-bold font-sans',
        'font-sans font-serif font-mono',
        'font-sans font-my-family',
        'font-bold font-[700]',
        'font-bold font-[weight:var(--w)]',
        'font-sans font-[family-name:var(--f)]',
        'font-stretch-expanded font-stretch-[66.66%] font-stretch-50%',
        'italic not-italic',
        'antialiased subpixel-antialiased',
        'uppercase lowercase capitalize normal-case',
        'underline overline line-through no-underline',
        'underline line-through',
        'line-through no-underline',
        'truncate text-ellipsis',
        'normal-nums ordinal',
        'ordinal normal-nums',
        'content-none content-[""]',
        "content-['hello'] content-[attr(data-content)]",
        'align-top align-[4px]',
        'indent-2 -indent-2',
    ],
    Merge_MatchesTailwindMerge_ForColorsAndBackgrounds: [
        'bg-grey-5 bg-grey-6',
        'bg-grey-5/10 bg-grey-6/50',
        'hover:bg-grey-5/10 hover:bg-grey-6/50',
        'bg-red-500 bg-blue-500/50',
        'bg-red-500/50 bg-red-500',
        'bg-red-500/[0.31] bg-red-500/[31%] bg-red-500/(--alpha)',
        'bg-transparent bg-current bg-inherit bg-black bg-white',
        'bg-my-brand bg-other-brand',
        'bg-red-500 bg-fixed bg-local',
        'bg-clip-border bg-clip-text',
        'bg-origin-border bg-origin-content',
        'bg-repeat bg-no-repeat bg-repeat-x',
        'bg-auto bg-cover bg-contain',
        'bg-center bg-top bg-left-top bg-bottom-right',
        'bg-red-500 bg-center bg-cover bg-no-repeat bg-fixed',
        'bg-none bg-gradient-to-r',
        'bg-gradient-to-r bg-gradient-to-b bg-none',
        'bg-linear-to-r bg-linear-45',
        'bg-linear-to-r bg-radial-[something] bg-conic-10',
        'bg-linear-to-r bg-red-500',
        'from-red-500 from-blue-500 via-red-500 via-blue-500 to-red-500 to-blue-500',
        'from-0% from-10% from-[12.5%]',
        'from-0% from-red',
        'via-0% via-10% via-[12.5%]',
        'to-0% to-10% to-[12.5%]',
        'from-0% to-10% via-5%',
        'from-red-500 from-10% via-blue-500 via-50% to-green-500 to-90%',
        'via-red-500 via-(--mobile-header-gradient)',
        'via-red-500 via-(length:--mobile-header-gradient)',
        'from-(--my-color) from-red-500',
        'fill-red-500 fill-(--my-fill) fill-[#fff]',
        'stroke-[hsl(350_80%_0%)] stroke-[10px]',
        'stroke-red-500 stroke-(--my-stroke) stroke-2',
        'accent-(--a) accent-red-500',
        'caret-(--a) caret-red-500',
        'border-t border-white/10',
        'border-t border-white',
        'border-white border-white/10',
        'border-t-some-blue border-t-other-blue',
        'border-t-some-blue border-some-blue',
        'border-some-blue border-s-some-blue',
        'border-e-some-blue border-some-blue',
        'border-2 border-solid border-red-500 border-4 border-dashed border-blue-500',
        'border border-0',
        'border-x border-x-2 border-y border-y-0',
        'ring-red-500 ring-2 ring-my-color ring-4',
        'ring-offset-red-500 ring-offset-2 ring-offset-my-color ring-offset-4',
        'outline-red-500 outline-2 outline-my-color outline-4',
        'decoration-red-500 decoration-my-color',
        'divide-red-500 divide-my-color',
        'shadow-red-500 shadow-my-color',
        'placeholder-red-500 placeholder-blue-500',
    ],
    Merge_MatchesTailwindMerge_ForArbitraryValues: [
        'm-[2px] m-[10px]',
        'm-[2px] m-[11svmin] m-[12in] m-[13lvi] m-[14vb] m-[15vmax] m-[16mm] m-[17%] m-[18em] m-[19px] m-[10dvh]',
        'h-[10px] h-[11cqw] h-[12cqh] h-[13cqi] h-[14cqb] h-[15cqmin] h-[16cqmax]',
        'z-20 z-[99]',
        'my-[2px] m-[10rem]',
        'cursor-pointer cursor-[grab]',
        'm-[2px] m-[calc(100%-var(--arbitrary))]',
        'm-[2px] m-[length:var(--mystery-var)]',
        'opacity-10 opacity-[0.025]',
        'scale-75 scale-[1.7]',
        'brightness-90 brightness-[1.75]',
        'min-h-[0.5px] min-h-[0]',
        'text-[0.5px] text-[color:0]',
        'text-[0.5px] text-(--my-0)',
        'hover:m-[2px] hover:m-[length:var(--c)]',
        'hover:focus:m-[2px] focus:hover:m-[length:var(--c)]',
        'border-b border-[color:rgb(var(--color-gray-500-rgb)/50%))]',
        'border-[color:rgb(var(--color-gray-500-rgb)/50%))] border-b',
        'border-b border-[color:rgb(var(--color-gray-500-rgb)/50%))] border-some-coloooor',
        'grid-rows-[1fr,auto] grid-rows-2',
        'grid-rows-[repeat(20,minmax(0,1fr))] grid-rows-3',
        'grid-cols-[1fr,auto] grid-cols-2',
        'mt-2 mt-[calc(theme(fontSize.4xl)/1.125)]',
        'p-2 p-[calc(theme(fontSize.4xl)/1.125)_10px]',
        'mt-2 mt-[length:theme(someScale.someValue)]',
        'mt-2 mt-[theme(someScale.someValue)]',
        'text-2xl text-[length:theme(someScale.someValue)]',
        'text-2xl text-[calc(theme(fontSize.4xl)/1.125)]',
        'text-2xl text-[theme(myCustomScale.rebecca)]',
        'text-red-500 text-[theme(myCustomScale.rebecca)]',
        'text-[calc(var(--rebecca)-1rem)] text-2xl',
        'text-[14px] text-[1rem] text-[clamp(1rem,2vw,2rem)]',
        'text-[#fff] text-[rgb(0_0_0)] text-[hsl(0_0%_0%)] text-[oklch(50%_0.1_200)]',
        'text-[#fff] text-[14px]',
        'text-[color:var(--c)] text-[length:var(--s)]',
        'text-(--my-color) text-red-500',
        'text-(length:--my-size) text-sm',
        'text-(color:--my-color) text-sm',
        'bg-cover bg-[percentage:30%] bg-[size:200px_100px] bg-[length:200px_100px]',
        'bg-none bg-[url(.)] bg-[image:.] bg-[url:.] bg-[linear-gradient(.)] bg-linear-to-r',
        'bg-red-500 bg-[url(./x.png)]',
        'bg-[url(./x.png)] bg-red-500',
        'bg-red-500 bg-[#B91C1C]',
        'bg-[#B91C1C] bg-radial-[at_50%_75%] bg-radial-[at_25%_25%]',
        'bg-center bg-[position:200px_100px]',
        'bg-center bg-[center_top_1rem]',
        'bg-black bg-(--my-color) bg-[color:var(--mystery-var)]',
        'bg-red bg-(--other-red) bg-bottom bg-(position:-my-pos)',
        'bg-(image:--my-img) bg-none',
        'bg-(length:--my-size) bg-cover',
        'border-[color-mix(in_oklab,var(--background),var(--calendar-color)_30%)] border',
        'border-[3px] border-[#fff] border-[5px] border-[#000]',
        'border-[length:var(--w)] border-[color:var(--c)] border-2 border-red-500',
        'border-(--my-color) border-red-500',
        'border-(length:--my-width) border-2',
        'border-t-[3px] border-t-[#fff] border-t-2',
        'shadow-xs shadow-(shadow:--something) shadow-red shadow-(--some-other-shadow) shadow-(color:--some-color)',
        'shadow-[0_1px_2px_black] shadow-lg shadow-[#fff] shadow-red-500',
        'shadow-[inset_0_1px_0_0_#fff] shadow-md',
        'ring-[3px] ring-[#fff] ring-2 ring-red-500',
        'ring-offset-[3px] ring-offset-[#fff] ring-offset-2',
        'outline-[3px] outline-[#fff] outline-2',
        'decoration-[3px] decoration-[#fff] decoration-2',
        'stroke-[3px] stroke-[#fff] stroke-2',
        'w-[10px] w-[20%] w-(--my-width) w-1/2',
        'w-(--my-width) w-4',
        'h-[calc(100vh-4rem)] h-screen',
        'p-(--my-padding) p-4',
        'inset-[5%] inset-0',
        'top-[5%] -top-[10%]',
        'rounded-[4px] rounded-lg rounded-[var(--r)]',
        'rounded-t-[4px] rounded-t-lg',
        'gap-[3px] gap-2',
        'duration-[250ms] duration-300',
        'ease-[cubic-bezier(0.4,0,0.2,1)] ease-in',
        'transition-[margin] transition-colors',
        'transition-all transition-[opacity,transform]',
        'rotate-45 rotate-[30deg]',
        'translate-x-[10px] translate-x-4',
        'aspect-[16/9] aspect-video',
        'columns-[10rem] columns-3',
        'basis-[30%] basis-1/3',
        'flex-[2_2_0%] flex-1',
        'order-[13] order-1',
        'leading-[1.2] leading-tight',
        'tracking-[.25em] tracking-wide',
        'blur-[2px] blur-sm',
        'animate-[wiggle_1s_ease-in-out_infinite] animate-spin',
        'origin-[33%_75%] origin-center',
        'will-change-[top,left] will-change-auto',
        'object-[25%_75%] object-center',
        'object-cover object-[25%_75%]',
        'mask-[url(./m.svg)] mask-none',
        'supports-[display:grid]:grid supports-[display:grid]:flex',
        'data-[state=open]:bg-red-500 data-[state=open]:bg-blue-500',
        'data-[state=open]:bg-red-500 data-[state=closed]:bg-blue-500',
        'aria-[sort=ascending]:p-1 aria-[sort=ascending]:p-2',
        'min-[400px]:p-1 min-[400px]:p-2 max-[600px]:p-3',
        'has-[[data-potato]]:p-1 has-[[data-potato]]:p-2 group-has-[:checked]:grid group-has-[:checked]:flex',
        'group-[.is-open]:block group-[.is-open]:hidden',
        'not-[.foo]:p-1 not-[.foo]:p-2',
        'in-[.dark]:p-1 in-[.dark]:p-2',
        'nth-[3n+1]:p-1 nth-[3n+1]:p-2',
    ],
    Merge_MatchesTailwindMerge_ForArbitraryProperties: [
        '[paint-order:markers] [paint-order:normal]',
        '[paint-order:markers] [--my-var:2rem] [paint-order:normal] [--my-var:4px]',
        '[paint-order:markers] hover:[paint-order:normal]',
        'hover:[paint-order:markers] hover:[paint-order:normal]',
        'hover:focus:[paint-order:markers] focus:hover:[paint-order:normal]',
        '[paint-order:markers] [paint-order:normal] [--my-var:2rem] lg:[--my-var:4px]',
        '[-unknown-prop:::123:::] [-unknown-prop:url(https://hi.com)]',
        '![some:prop] [some:other]',
        '![some:prop] [some:other] [some:one] ![some:another]',
        '[some:prop]! [some:other]!',
        '[mask-type:luminance] [mask-type:alpha]',
        '[--scroll-offset:56px] lg:[--scroll-offset:44px]',
        '[padding:1rem] p-8',
        'p-8 [padding:1rem]',
        '[color:red] text-blue-500',
        '[&>*]:[color:red] [&>*]:[color:blue]',
        '[&[data-foo][data-bar]:not([data-baz])]:nod:noa:[color:red] [&[data-foo][data-bar]:not([data-baz])]:noa:nod:[color:blue]',
    ],
    Merge_MatchesTailwindMerge_ForArbitraryVariants: [
        '[p]:underline [p]:line-through',
        '[&>*]:underline [&>*]:line-through',
        '[&>*]:underline [&>*]:line-through [&_div]:line-through',
        'supports-[display:grid]:flex supports-[display:grid]:grid',
        'dark:lg:hover:[&>*]:underline dark:lg:hover:[&>*]:line-through',
        'dark:lg:hover:[&>*]:underline dark:hover:lg:[&>*]:line-through',
        'hover:[&>*]:underline [&>*]:hover:line-through',
        'hover:dark:[&>*]:underline dark:hover:[&>*]:underline',
        'hover:dark:[&>*]:underline dark:[&>*]:hover:line-through',
        '[&[data-open]]:underline [&[data-open]]:line-through',
        '[&[data-foo][data-bar]:not([data-baz])]:underline [&[data-foo][data-bar]:not([data-baz])]:line-through',
        '[&>*]:[&_div]:underline [&>*]:[&_div]:line-through',
        '[&>*]:[&_div]:underline [&_div]:[&>*]:line-through',
        'hover:dark:[&>*]:focus:disabled:[&_div]:underline dark:hover:[&>*]:disabled:focus:[&_div]:line-through',
        'hover:dark:[&>*]:focus:[&_div]:disabled:underline dark:hover:[&>*]:disabled:focus:[&_div]:line-through',
        '[&:nth-child(3)]:py-0 [&:nth-child(3)]:py-4',
        '[&:focus]:ring focus:ring-4',
        '[&:focus]:ring-2 [&:focus]:ring-4',
        '[@media(min-width:400px)]:p-1 [@media(min-width:400px)]:p-2',
        '[@supports(display:grid)]:grid [@supports(display:grid)]:flex',
        '[&>*]:px-4 [&>p]:px-2',
        '[&_a:hover]:text-red-500 [&_a:hover]:text-blue-500',
    ],
    Merge_MatchesTailwindMerge_ForTheImportantModifier: [
        '!font-medium !font-bold',
        '!font-medium !font-bold font-thin',
        '!right-2 !-inset-x-px',
        'focus:!inline focus:!block',
        '[&>*]:!underline [&>*]:!line-through',
        'font-medium! font-bold!',
        'font-medium! font-bold! font-thin',
        'right-2! -inset-x-px!',
        'focus:inline! focus:block!',
        'p-3! p-4! p-5',
        'p-5 p-3! p-4!',
        '!p-3 p-4!',
        'p-3! !p-4',
        '!p-3 p-3',
        'hover:!p-3 hover:p-4! hover:p-5',
        '!-mt-2 !mt-4',
        '-mt-2! mt-4!',
        '!text-sm/6 !leading-4',
        '!leading-4 !text-sm/6',
        'leading-4 !text-sm/6',
        '!bg-red-500/50 !bg-blue-500',
        '!w-[10px] !w-[20px]',
        'w-(--a)! w-4!',
    ],
    Merge_MatchesTailwindMerge_ForModifiers: [
        'hover:block hover:inline',
        'hover:block hover:focus:inline',
        'hover:block hover:focus:inline focus:hover:inline',
        'focus-within:inline focus-within:block',
        'focus-visible:inline focus:block',
        'c:d:e:block d:c:e:inline',
        '*:before:block *:before:inline',
        '*:before:block before:*:inline',
        'x:y:*:z:block y:x:*:z:inline',
        'x:y:*:z:block y:x:z:*:inline',
        '*:p-10 *:p-20 hover:*:p-10 hover:*:p-20',
        '**:p-10 **:p-20 hover:**:p-10 hover:**:p-20',
        '*:p-1 **:p-2',
        'before:hover:block hover:before:inline',
        'before:block before:inline',
        'after:hover:p-1 hover:after:p-2',
        'placeholder:hover:p-1 hover:placeholder:p-2',
        'file:hover:p-1 hover:file:p-2',
        'marker:hover:p-1 hover:marker:p-2',
        'selection:hover:p-1 hover:selection:p-2',
        'first-line:hover:p-1 hover:first-line:p-2',
        'first-letter:hover:p-1 hover:first-letter:p-2',
        'backdrop:hover:p-1 hover:backdrop:p-2',
        'hover:focus:active:p-1 active:hover:focus:p-2',
        'sm:p-1 md:p-2 lg:p-3 xl:p-4 2xl:p-5 sm:p-6',
        'sm:md:p-1 md:sm:p-2',
        'max-sm:p-1 max-sm:p-2 sm:max-md:p-3 max-md:sm:p-4',
        '@sm:p-1 @sm:p-2 @md:p-3',
        '@container/main @container/sidebar',
        '@sm/main:p-1 @sm/main:p-2 @sm/sidebar:p-3',
        'dark:hover:bg-red-500 hover:dark:bg-blue-500',
        'dark:bg-red-500 light:bg-blue-500',
        'print:hidden print:block',
        'motion-safe:animate-spin motion-safe:animate-none motion-reduce:animate-none',
        'rtl:ml-2 rtl:ml-4 ltr:ml-2',
        'portrait:p-1 landscape:p-2 portrait:p-3',
        'contrast-more:p-1 contrast-more:p-2',
        'forced-colors:p-1 forced-colors:p-2',
        'open:p-1 open:p-2',
        'starting:opacity-0 starting:opacity-50',
        'pointer-fine:p-1 pointer-coarse:p-2 pointer-fine:p-3',
        'empty:p-2 empty:p-3',
        'hover:empty:p-2 hover:empty:p-3',
        'read-only:p-2 read-only:p-3',
        'group-empty:p-2 group-empty:p-3',
        'peer-empty:p-2 peer-empty:p-3',
        'group-empty:p-2 peer-empty:p-3',
        'hover:group-empty:p-2 hover:group-empty:p-3',
        'group-read-only:p-2 group-read-only:p-3',
        'group-hover:p-1 group-hover:p-2 peer-hover:p-3',
        'group-hover/item:p-1 group-hover/item:p-2 group-hover/other:p-3',
        'peer-checked/draft:p-1 peer-checked/draft:p-2',
        'first:p-1 last:p-2 odd:p-3 even:p-4 first:p-5',
        'disabled:opacity-50 disabled:opacity-75 enabled:opacity-100',
        'aria-checked:p-1 aria-checked:p-2 aria-disabled:p-3',
        'data-active:p-1 data-active:p-2',
        'not-hover:p-1 not-hover:p-2',
        'has-checked:p-1 has-checked:p-2',
        'in-focus:p-1 in-focus:p-2',
        'nth-3:p-1 nth-3:p-2 nth-last-3:p-3',
        'inert:p-1 inert:p-2',
        'hover:p-2 p-4 hover:p-4 p-2',
        'md:hover:focus:p-1 focus:hover:md:p-2 hover:md:focus:p-3',
    ],
    Merge_MatchesTailwindMerge_ForNegativeValues: [
        '-m-2 -m-5',
        '-top-12 -top-2000',
        '-m-2 m-auto',
        'top-12 -top-69',
        '-right-1 inset-x-1',
        'hover:focus:-right-1 focus:hover:inset-x-1',
        '-inset-1 inset-x-px',
        'inset-x-px -inset-1',
        'bottom-auto inset-y-6',
        '-mx-2 mx-2 -mx-4',
        '-translate-x-1 translate-x-2 -translate-y-1',
        '-rotate-45 rotate-45',
        '-skew-x-3 skew-x-6',
        '-scale-x-50 scale-x-50',
        '-space-x-2 space-x-2',
        '-z-10 z-10',
        '-order-1 order-1',
        '-indent-2 indent-2',
        '-tracking-2 tracking-tight',
        '-hue-rotate-15 hue-rotate-30',
        '-backdrop-hue-rotate-15 backdrop-hue-rotate-30',
        '-scroll-m-2 scroll-m-4',
        '-outline-offset-2 outline-offset-2',
        '-underline-offset-2 underline-offset-2',
        '-mt-[2px] mt-[4px]',
        '-top-(--a) top-2',
        'hover:-mt-2 hover:mt-4 -mt-1',
    ],
    Merge_MatchesTailwindMerge_ForNonTailwindClasses: [
        'non-tailwind-class inline block',
        'inline block inline-1',
        'inline block i-inline',
        'focus:inline focus:block focus:inline-1',
        'p-5 p-2 my-non-tailwind-class p-4',
        'btn btn-primary btn-lg',
        'peer group peer/draft group/item',
        'foo foo bar foo',
        'px-4 foo px-2 foo',
        'tw-icon-pulse tw-icon-pulse',
        'card card-flat card',
        'hover:foo hover:foo',
        'bi bi-house bi-house-fill',
        'prose prose-lg prose-slate',
        'flexbox flex-container flex',
        'blocky block',
        'paddingx px-2 px-4',
        'half w-1/2 w-half',
        'js-toggle is-open has-icon',
        'a b c a',
    ],
    Merge_MatchesTailwindMerge_ForStandaloneClasses: [
        'inline block',
        'hover:block hover:inline',
        'hover:block hover:block',
        'inline hover:inline focus:inline hover:block hover:focus:block',
        'underline line-through',
        'line-through no-underline',
        'block inline-block inline flex inline-flex table inline-table grid inline-grid contents list-item hidden flow-root',
        'table-caption table-cell table-column table-row table-row-group table-header-group table-footer-group table-column-group',
        'hidden block md:hidden md:flex',
        'container block',
        'container container',
        'truncate truncate',
        'italic italic not-italic',
        'ring ring',
        'border border',
        'rounded rounded',
        'shadow shadow',
        'blur blur',
        'transition transition',
        'grow shrink grow shrink',
        'outline outline',
        'resize resize',
        'invert invert grayscale grayscale sepia sepia',
    ],
    Merge_MatchesTailwindMerge_ForWhitespaceAndOrder: [
        'px-4 px-2',
        ' px-4  px-2 ',
        '  block\n  px-2     py-4  ',
        '\tblock\tinline\t',
        'block\npx-2\n\n\npx-4',
        'a px-4 c e px-3 px-2 b',
        'px-2 a px-4 b px-2',
        'p-1 m-1 p-2 m-2 p-3 m-3',
        'flex px-4 py-2 items-center px-2 justify-between py-1 block',
        'block',
        'unknown',
    ],
    // A Tailwind v4 prefix is written like a variant (tw:px-4), so prefixed classes merge with each other and
    // never with the unprefixed class of the same name.
    Merge_MatchesTailwindMerge_ForPrefixedClasses: [
        'tw:px-4 tw:px-2',
        'tw:hover:px-4 tw:hover:px-2',
        'tw:px-4 px-2',
        'px-4 tw:px-2',
        'px-4 tw:px-4 px-2 tw:px-2',
        'tw:px-4 hover:tw:px-2',
        'tw:p-4 tw:px-2 tw:pl-1 tw:px-3',
        'tw:text-sm tw:leading-6 tw:text-lg/7',
        'tw:px-4! tw:px-2!',
        'tw:px-4! tw:px-2',
        'tw:dark:hover:bg-red-500 tw:hover:dark:bg-blue-500',
        'tw:-mt-2 tw:mt-4',
        'tw:flex tw:block tw:md:flex tw:md:grid',
        'tw:bg-red-500 tw:bg-[#fff] tw:bg-(--brand)',
        'tw:[&>*]:p-1 tw:[&>*]:p-2',
        'tw:before:hover:p-1 tw:hover:before:p-2',
        'customprefix:py-3 customprefix:py-1 customprefix:p-2',
        'customprefix:py-3 customprefix:p-2 customprefix:pt-1',
        'tw:my-custom-class tw:my-custom-class',
    ],
    Merge_MatchesTailwindMerge_ForRealWorldComponentClasses: [
        'inline-flex items-center justify-center rounded-md text-sm font-medium px-4 py-2 bg-blue-600 text-white hover:bg-blue-700 px-2 bg-red-600 hover:bg-red-700',
        'flex items-center gap-2 px-3 py-2 text-sm text-gray-700 hover:bg-gray-100 rounded-lg rounded-none font-semibold font-normal',
        'w-full h-10 rounded border border-gray-300 bg-white px-3 text-base focus:outline-none focus:ring-2 focus:ring-blue-500 h-12 border-red-500 focus:ring-red-500',
        'absolute inset-0 z-10 bg-black/50 backdrop-blur-sm fixed z-50 bg-black/75',
        'grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 grid-cols-2 gap-6 lg:grid-cols-4',
        'text-sm font-medium text-gray-900 dark:text-white text-lg dark:text-gray-100 text-red-600',
        'transition-colors duration-200 ease-in-out transition-all duration-300',
        'shadow-sm ring-1 ring-black/5 shadow-lg ring-2 ring-blue-500/50',
        'border-b border-gray-200 dark:border-gray-700 border-b-2 border-transparent dark:border-transparent',
        'min-w-0 flex-1 truncate text-left whitespace-normal overflow-visible',
        'size-8 shrink-0 rounded-full bg-gray-100 size-10 rounded-lg',
        'mt-2 mb-4 mx-auto max-w-2xl my-8 max-w-4xl',
        'p-4 sm:p-6 lg:p-8 px-2 sm:px-4 lg:p-10',
        'opacity-0 scale-95 transition duration-150 opacity-100 scale-100',
        'disabled:opacity-50 disabled:cursor-not-allowed disabled:opacity-75 disabled:pointer-events-none',
        'focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600 focus-visible:outline-none focus-visible:outline-red-600',
        'bg-linear-to-r from-purple-700 to-fuchsia-600 dark:from-purple-400 dark:to-fuchsia-300 from-blue-700 dark:to-blue-300',
        'h-dvh w-64 overflow-auto overscroll-contain border-e border-gray-200 w-72 overflow-y-auto',
        'text-[oklch(21%_0.006_285.885)] dark:text-[oklch(97.807%_0.029_256.847)] text-sm text-[oklch(40%_0.016_253)]',
        'hover:bg-[oklch(98%_0_0)] hover:bg-[oklch(95%_0_0)] bg-[oklch(100%_0_0)] bg-white',
    ],
};

// Inputs merged with the prefix option set to "tw", by both tailwind-merge and TwBlazor.
export const prefixCorpus = [
    'tw:px-4 tw:px-2',
    'px-4 px-2',
    'tw:px-4 px-2',
    'px-4 tw:px-2',
    'hidden block tw:hidden tw:block',
    'container tw:container flex tw:flex tw:grid',
    'tw:hover:px-4 tw:hover:px-2',
    'tw:hover:px-4 hover:tw:px-2',
    'hover:tw:px-4 hover:tw:px-2',
    'tw:p-4 tw:px-2 tw:pl-1 tw:px-3',
    'tw:pl-1 tw:pr-1 tw:px-3',
    'tw:text-sm tw:leading-6 tw:text-lg/7',
    'tw:px-4! tw:px-2!',
    'tw:px-4! tw:px-2',
    'tw:dark:hover:bg-red-500 tw:hover:dark:bg-blue-500',
    'tw:before:hover:p-1 tw:hover:before:p-2',
    'tw:-mt-2 tw:mt-4',
    'tw:bg-red-500 tw:bg-[#fff] tw:bg-(--brand)',
    'tw:[&>*]:p-1 tw:[&>*]:p-2',
    'tw:[mask-type:alpha] tw:[mask-type:luminance]',
    'tw:w-1/2 tw:w-half tw:w-full',
    'tw:my-class tw:my-class other other',
    'fable:px-4 fable:px-2 tw:m-4 tw:m-2',
    'tw: tw:flex tw:block',
];

// Inputs above that TwBlazor deliberately merges differently from tailwind-merge. They are left out of the parity
// tests and covered in TwClassMergerTests instead.
export const knownDifferences = [
    // tailwind-merge miscounts the position of a "/" modifier after a leading "!" (the Tailwind v3 important
    // syntax), so it reads "!text-sm/6" as a text color and keeps the leading class before it.
    '!leading-4 !text-sm/6',

    // tailwind-merge reads an unlabelled arbitrary background value it cannot identify as a color. Tailwind reads
    // one made of position keywords as a background position, and so does TwBlazor.
    'bg-center bg-[center_top_1rem]',
];
