// Generates, from the tailwind-merge npm package pinned in package.json:
//
//   src/TwBlazor/Utilities/ClassMerge/TwClassGroups.Data.cs
//       The class groups, conflicts and order sensitive modifiers of tailwind-merge's default config.
//
//   tests/TwBlazor.Tests/Utilities/ClassMerge/TwClassMergerParityTests.cs
//       One test case per input in corpus.mjs, expecting exactly what twMerge returns for it.
//
// Usage (from this folder): npm install, then npm run generate.
// To move to a newer tailwind-merge, change its version in package.json and run both again.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { getDefaultConfig, twMerge, validators } from 'tailwind-merge';
import { corpus, knownDifferences } from './corpus.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..', '..');
const version = JSON.parse(readFileSync(resolve(here, 'node_modules/tailwind-merge/package.json'), 'utf8')).version;

const quote = text => '"' + text.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\t/g, '\\t') + '"';
const write = (path, content) => writeFileSync(resolve(repoRoot, path), content.replace(/\n/g, '\r\n'));

// --- Class groups --------------------------------------------------------------------------------------------

const config = getDefaultConfig();
const validatorNames = new Map(Object.entries(validators).map(([name, validator]) => [validator, name.replace(/^is/, '')]));
const definitions = [];

// Mirrors processClassesRecursively in tailwind-merge's class-group-utils.ts, recording each definition
// against the dash separated path it is registered under instead of building the lookup tree.
function walk(group, path, classDefinitions) {
    for (const definition of classDefinitions) {
        if (typeof definition === 'string') {
            definitions.push({ group, path: [path, definition].filter(part => part !== '').join('-'), validator: null });
        } else if (typeof definition === 'function') {
            if (definition.isThemeGetter) {
                walk(group, path, definition(config.theme));
            } else if (validatorNames.has(definition)) {
                definitions.push({ group, path, validator: validatorNames.get(definition) });
            } else {
                throw new Error(`Class group "${group}" uses a validator this script does not know: ${definition}`);
            }
        } else {
            for (const [key, value] of Object.entries(definition)) {
                walk(group, [path, key].filter(part => part !== '').join('-'), value);
            }
        }
    }
}

for (const [group, classDefinitions] of Object.entries(config.classGroups)) {
    walk(group, '', classDefinitions);
}

const stringList = values => `[${values.map(quote).join(', ')}]`;
const dictionary = map => Object.entries(map).map(([key, values]) => `            [${quote(key)}] = ${stringList(values)},`).join('\n');

write('src/TwBlazor/Utilities/ClassMerge/TwClassGroups.Data.cs', `// Copyright (c) 2025 Jack Shuter @ TwBlazor - twblazor.com
// Licensed under the MIT License. See LICENSE.txt in the project root for license information.

// <auto-generated>
// Generated by scripts/class-merge/generate.mjs from the default config of tailwind-merge ${version}
// (https://github.com/dcastil/tailwind-merge, MIT License, Copyright (c) 2021 Dany Castillo).
// Do not edit by hand. Change the tailwind-merge version in scripts/class-merge/package.json and run the script.
// </auto-generated>

namespace TwBlazor.Utilities.ClassMerge;

internal static partial class TwClassGroups
{
    /// <summary>
    /// The version of the tailwind-merge package the tables in this file were generated from.
    /// </summary>
    public const string TailwindMergeVersion = ${quote(version)};

    private static string[] BuildOrderSensitiveModifiers() => ${stringList(config.orderSensitiveModifiers)};

    private static string[] BuildPostfixLookupGroups() => ${stringList(config.postfixLookupClassGroups ?? [])};

    private static Dictionary<string, string[]> BuildConflicts() =>
        new(StringComparer.Ordinal)
        {
${dictionary(config.conflictingClassGroups)}
        };

    private static Dictionary<string, string[]> BuildModifierConflicts() =>
        new(StringComparer.Ordinal)
        {
${dictionary(config.conflictingClassGroupModifiers)}
        };

    private static TwClassDefinition[] BuildDefinitions() =>
    [
${definitions.map(d => `        new(${quote(d.group)}, ${quote(d.path)}${d.validator ? `, TwClassValidator.${d.validator}` : ''}),`).join('\n')}
    ];
}
`);

// --- Parity tests ----------------------------------------------------------------------------------------------

let caseCount = 0;
let theories = '';

for (const [name, inputs] of Object.entries(corpus)) {
    const cases = [...new Set(inputs)].filter(input => !knownDifferences.includes(input));
    caseCount += cases.length;

    theories += '\n    [Theory]\n';
    theories += cases.map(input => `    [InlineData(${quote(input)}, ${quote(twMerge(input))})]\n`).join('');
    theories += `    public void ${name}(string input, string expected)\n    {\n        Assert.Equal(expected, _merger.Merge(input));\n    }\n`;
}

write('tests/TwBlazor.Tests/Utilities/ClassMerge/TwClassMergerParityTests.cs', `// <auto-generated>
// Generated by scripts/class-merge/generate.mjs. Do not edit by hand: add inputs to scripts/class-merge/corpus.mjs
// and run the script, which asks tailwind-merge for the expected value of each one.
// </auto-generated>

using TwBlazor.Configuration;
using TwBlazor.Utilities.ClassMerge;

namespace TwBlazor.Tests.Utilities.ClassMerge;

/// <summary>
/// Checks <see cref="TwClassMerger"/> against the tailwind-merge npm package. Every expected value is what
/// <c>twMerge</c> from tailwind-merge ${version} returns for the same input, so a failure here is a difference from
/// that package.
/// </summary>
public class TwClassMergerParityTests
{
    private static readonly TwClassMerger _merger = new(new TwClassMergeOptions());

    [Fact]
    public void Tables_AreGeneratedFromTheSameTailwindMergeVersion_AsTheseTests()
    {
        Assert.Equal(${quote(version)}, TwClassGroups.TailwindMergeVersion);
    }
${theories}}
`);

console.log(`tailwind-merge ${version}: ${definitions.length} class definitions, ${caseCount} parity cases.`);
