<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TwBlazor.Docs\TwBlazor.Docs.csproj" />
    <ProjectReference Include="..\..\src\TwBlazor.Theme\TwBlazor.Theme.csproj" />
  </ItemGroup>

</Project>
