<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\build\TwBlazor.Docs.Compiler\TwBlazor.Docs.Compiler.csproj" />
    <ProjectReference Include="..\TwBlazor\TwBlazor.csproj" />
  </ItemGroup>

</Project>
