// Copyright (c) 2025 Jack Shuter @ TwBlazor - twblazor.com
// Licensed under the MIT License. See LICENSE.txt in the project root for license information.

using Microsoft.AspNetCore.Components;
using TwBlazor.Abstraction;
using TwBlazor.Builders;
using TwBlazor.Configuration;
using TwBlazor.Enums;

namespace TwBlazor;

public class TwBlazorComponentBase : ComponentBase, ITwComponent
{
    [Inject] protected TwBlazorOptions options { get; set; } = null!;

    [Inject] protected RoundedBuilder roundedBuilder { get; set; } = null!;
    [Inject] protected ShadowBuilder shadowBuilder { get; set; } = null!;
    [Inject] protected ColorBuilder colorBuilder { get; set; } = null!;
    [Inject] protected IconColorBuilder iconColorBuilder { get; set; } = null!;
    [Inject] protected PopoverBuilder popoverBuilder { get; set; } = null!;

    /// <inheritdoc cref="ITwComponent.Id" />
    [Parameter] public string? Id { get; set; }

    /// <inheritdoc cref="ITwComponent.Class" />
    [Parameter] public string Class { get; set; } = string.Empty;

    /// <inheritdoc cref="ITwComponent.Style" />
    [Parameter] public string? Style { get; set; }

    /// <inheritdoc cref="ITwComponent.Attributes" />
    [Parameter(CaptureUnmatchedValues = true)] public Dictionary<string, object> Attributes { get; set; } = [];

    /// <inheritdoc cref="ITwComponent.AriaLabel" />
    [Parameter] public string? AriaLabel { get; set; }

    /// <inheritdoc cref="ITwComponent.AriaLabelledBy" />
    [Parameter] public string? AriaLabelledBy { get; set; }

    /// <inheritdoc cref="ITwComponent.Shadow" />
    [Parameter] public Shadow? Shadow { get; set; }

    /// <inheritdoc cref="ITwComponent.Rounded" />
    [Parameter] public Rounded? Rounded { get; set; }

    /// <summary>
    /// Gets the effective shadow to use, considering both the parameter and global configuration.
    /// </summary>
    protected Shadow effectiveShadow => Shadow ?? options.Theme.Shadows.DefaultShadow;

    /// <summary>
    /// Gets the effective rounded to use, considering both the parameter and global configuration.
    /// </summary>
    protected Rounded effectiveRounded => Rounded ?? options.Theme.Rounded.DefaultRounded;

    /// <summary>
    /// Invoked when the component's parameters have been set. Ensures that the component has a unique identifier by
    /// generating one if none is provided.
    /// </summary>
    /// <remarks>If the component's identifier is not set, a unique ID is generated based on the component's
    /// type name (with a 'Tw' prefix removed if present) and a GUID. This helps ensure that each component instance can
    /// be uniquely identified, which is useful for scenarios such as associating labels with form elements or targeting
    /// elements in client-side scripts.</remarks>
    protected override void OnParametersSet()
    {
        base.OnParametersSet();

        // Remember whether the Id was explicitly provided by the consumer. We record this before
        // generating a new Id so callers can distinguish a user-supplied Id from an auto-generated one.
        hasUserProvidedId = !string.IsNullOrEmpty(Id);

        // Generate a unique ID if not provided
        if (string.IsNullOrEmpty(Id))
        {
            var componentName = GetType().Name;

            // Remove generic type indicator '`'.
            var backtickIndex = componentName.IndexOf('`');
            if (backtickIndex > 0)
            {
                componentName = componentName.Substring(0, backtickIndex);
            }

            // Remove "Tw" prefix if present
            if (componentName.StartsWith("Tw"))
            {
                componentName = componentName.Substring(2);
            }

            Id = $"{componentName.ToLower()}-{Guid.NewGuid():N}";
        }
    }

    /// <summary>
    /// Indicates whether an Id was explicitly provided by the consumer (true) or auto-generated by
    /// TwBlazorComponentBase (false).
    /// </summary>
    protected bool hasUserProvidedId { get; private set; }
}