name: CI Build

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build and Test (push)
    uses: ./.github/workflows/build-and-test.yml
    with:
      configuration: Release
      run-accessibility-tests: true
